sudo: required

language: python

services:
  - docker

before_install:
- docker pull iquod/autoqc

script:
- docker run iquod/autoqc /bin/bash -c "cd /AutoQC; git pull origin master; nosetests tests/*.py"
